---
- name: Install Nginx 
  apt: 
    name=nginx
    state=latest
    update_cache=yes

- name: Copy Nginx conf file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'files/nginx.conf',        dest: '/etc/nginx/' }
    - { src: 'files/.htpasswd',         dest: '/etc/nginx/' }
    - { src: 'files/index.html',        dest: '/var/www/{{ domain }}/' }
    - { src: 'files/{{ domain }}.key',  dest: '/etc/ssl/{{ domain }}/' }
    - { src: 'files/{{ domain }}.crt',  dest: '/etc/ssl/{{ domain }}/' }
  notify:
    - reload nginx

- name: Copy {{ domain }}.{{ tld }} conf file
  template:
    src=templates/{{ domain }}.j2
    dest=/etc/nginx/sites-enabled/{{ domain }}.conf
  notify:
    - reload nginx