---
- name: Install Nginx
  apt:
    name: nginx=nginx=1.10.3
    state: present
    update_cache: yes

- name: Create nginx user
  user:
    name: nginx
    group: nginx
    password_lock: yes

- name: Copy necessary files
  copy: src=files/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '.htpasswd',         dest: '/etc/nginx/' }
    - { src: 'index.html',        dest: '/var/www/{{ domain }}/' }
    - { src: '{{ domain }}.key',  dest: '/etc/ssl/{{ domain }}/' }
    - { src: '{{ domain }}.crt',  dest: '/etc/ssl/{{ domain }}/' }
  notify:
    - reload nginx

- name: Copy templates
  template: src=templates/{{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - { src: '{{ domain }}',    dest: '/etc/nginx/conf.d/{{ domain }}.conf' }
    - { src: 'nginx',           dest: '/etc/nginx/nginx.conf' }
  notify:
    - reload nginx

- name: Change permissions
  file:
    path: /etc/nginx
    recurse: yes
    owner: nginx
    group: nginx

- name: Change permissions
  file:
    path: /var/www/{{ domain }}
    recurse: yes
    owner: nginx
    group: nginx