---
- name: Install Nginx 
  apt: 
    name=nginx
    state=latest
    update_cache=yes

- name: Copy Nginx conf file
  copy:
    src=files/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Copy {{ domain }}.{{ tld }} conf file
  template:
    src=templates/{{ domain }}.j2
    dest=/etc/nginx/sites-enabled/{{ domain }}.conf
  notify:
    - Reload nginx

- name: Copy index html file
  copy:
    src=files/index.html
    dest=/var/www/{{ domain }}/
  notify:
    - Reload nginx

- name: Copy auth file
  copy:
    src=files/.htpasswd
    dest=/etc/nginx/.htpasswd
  notify:
    - Reload nginx
    
- name: Copy SSL files
  copy:
    src=files/{{item}}
    dest=/etc/ssl/{{ domain }}/
  with_items:
    ['{{ domain }}.key', '{{ domain }}.crt']
  notify:
    - Reload nginx