---
- name: Install Nginx 
  apt: 
    name=nginx
    state=latest

- name: Copy conf file
  template:
    src=templates/{{ domain }}.j2
    dest=/etc/nginx/sites-enabled/{{ domain }}.conf

- name: Copy index html file
  copy:
    src=files/index.html
    dest=/var/www/{{ domain }}/

- name: Copy auth file
  copy:
    src=files/.htpasswd
    dest=/etc/nginx/.htpasswd

- name: Copy SSL files
  copy:
    src=files/{{item}}
    dest=/etc/ssl/{{ domain }}/
  with_items:
    ['{{ domain }}.key', '{{ domain }}.crt']
  notify:
    - nginx systemd