---
- name: Save iptable rules and make them on boot
  shell: |
    iptables-save > {{ iptable_rules }}
    cat /etc/network/interfaces | grep "pre-up iptables-restore" || echo "pre-up iptables-restore < {{ iptable_rules }}" >> /etc/network/interfaces