#!/bin/bash

IFS=$'\n'

FLYWAY_MIGRATIONS_FOLDER=test/resources/db/migrations
JAVA_MIGRATIONS_FOLDER=test/java/migrations
FLYWAY_FILES=()
JAVA_FILES=()

EXCLUDED_FILE=readme.md
RED='\e[91m'
GREEN='\e[92m'
NC='\033[0m' # No Color


sql_check () {
    for i in `find $1 -regextype posix-extended -not -regex '$2'`; do 
    if [[ $i != $1 ]]; then
        FILE=$(git status | grep $i)

    if [ ! -z "$FILE" ]; then
        FILES+=("$FILE")
    fi
    fi
    done

    if [ ! -z "$FILES" ]; then
        echo ""
        echo -e "${RED}The following migration files do not match the pattern: \n${FILES[*]}${NC}"
        echo ""
        echo -e "${GREEN}Please make sure to stick to the naming convention: \n$3"
        echo ""
        exit 1
    fi
}

sql_check $FLYWAY_MIGRATIONS_FOLDER "^.*V[0-9]{14}__.*.\.sql|^.*R_.*.\.sql" "https://github.com/Mercato-com/mercato/blob/master/mercato/resources/db/migration/main/readme.md"
sql_check $JAVA_MIGRATIONS_FOLDER "^.*V[0-9]{14}__.*.\.java|^.*R_.*.\.java" "https://github.com/Mercato-com/mercato/blob/master/mercato/src-core/db/migration/main/readme.md"