#!/bin/bash

IFS=$'\n'

FLYWAY_MIGRATIONS_FOLDER=test/resources/db/migrations
FLYWAY_FILES=()
JAVA_FILES=()

EXCLUDED_FILE=readme.md
RED='\e[91m'
GREEN='\e[92m'
NC='\033[0m' # No Color

for i in `find $FLYWAY_MIGRATIONS_FOLDER -regextype posix-extended -not -regex '^.*V[0-9]{14}__.*.\.sql|^.*R_.*.\.sql' | grep -v $EXCLUDED_FILE`; do 
if [[ $i != $FLYWAY_MIGRATIONS_FOLDER ]]; then
    FILE=$(git status | grep $i)

if [ ! -z "$FILE" ]; then
    FLYWAY_FILES+=("$FILE")
fi
fi
done

if [ ! -z "$FLYWAY_FILES" ]; then
    echo ""
    echo -e "${RED}The following Flyway migration files do not match the pattern: \n${FLYWAY_FILES[*]}${NC}"
    echo ""
    echo ""
    exit 1
fi
