galaxy_info:
  author: Artem Kulish
  description: role for the Iptables configuration on Debian/Ubuntu
  company: NA

  license: NA

  platforms:
    - name: Debian/Ubuntu

  min_ansible_version: 1.2

  github_branch: stage

  galaxy_tags: []

dependencies: []