name: Execution of ansible-lint 

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: sudo apt update && sudo pip install ansible-lint
    
    - name: Ansible-lint
      run: ls
