name: Execution of ansible-lint 

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: sudo apt update && sudo pip install ansible-lint
    
    - name: Clone the repo
      uses: actions/checkout@v1
      
    - name: Ansible-lint
      run: |
           ls
           pwd
           ansible-lint iptables nginx
