name: SQL pattern check

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pre-commit hook
      run: bash .githooks/pre-commit
