name: Execution of ansible-lint 

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pre-commit hook
      run: ls -la
